spring:
  application:
    name: SELEXTrace
  
  config:
    # This file must be created locally.
    # It is excluded from Git via .gitignore.
    import: "optional:file:.secrets.yml"

  datasource:
    # These variables can be defined inside .secrets.yml.
    # Example:
    # POSTGRES_URL: jdbc:postgresql://localhost:5432/selextrace
    # POSTGRES_USER: username
    # POSTGRES_PASSWORD: password
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB

selextrace:
  files:
    upload-dir: "./.data/files-spring"