[versions]
spring-boot = "4.0.3"
spring-dependency-management = "1.1.7"
milib = "2.3.0"
eclipse-collections = "13.0.0"
bloom-filter = "2.2.2"
commons-math3 = "3.6.1"
fastutil = "8.5.18"

[libraries]
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-boot-starter-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc" }
h2 = { module = "com.h2database:h2" }
postgresql = { module = "org.postgresql:postgresql" }
spring-boot-starter-data-jpa-test = { module = "org.springframework.boot:spring-boot-starter-data-jpa-test" }
spring-boot-starter-security-test = { module = "org.springframework.boot:spring-boot-starter-security-test" }
spring-boot-starter-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

milib = { module = "com.milaboratory:milib", version.ref = "milib" }
eclipse-collections = { module = "org.eclipse.collections:eclipse-collections", version.ref = "eclipse-collections" }
eclipse-collections-api = { module = "org.eclipse.collections:eclipse-collections-api", version.ref = "eclipse-collections" }
bloom-filter = { module = "com.baqend:bloom-filter", version.ref = "bloom-filter" }
commons-math3 = { module = "org.apache.commons:commons-math3", version.ref = "commons-math3" }
fastutil = { module = "it.unimi.dsi:fastutil", version.ref = "fastutil" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
