package pablog.aptasuite.lib.capr;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import java.io.DataInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.Objects;

import org.junit.jupiter.api.Test;

/// Regression test ensuring the refactored CapR implementation produces identical
/// structural profile output to the original version.
///
/// The fixture file (structural\_profile.bin) was generated by running the pre-refactor
/// code on a known input sequence and serializing the resulting double[] to binary.
class CapRTest {

    @Test
    void computeStructuralProfileMatchesFixture() throws IOException {
        String sequence = "GGGAGACAAGAATAAACGCTCAACAAACAACAGTACGTAGCATGCATGCTAGCTAGCTACTATGGGATTCGACAGGAGGCTCACAACAGGC";
        byte[] sequenceBytes = sequence.getBytes();

        CapR capr = new CapR();
        capr.ComputeStructuralProfile(sequenceBytes, sequence.length());

        double[] actual = capr.getStructuralProfile();
        double[] expected = loadProfileFixture("/capr/structural_profile.bin");

        assertEquals(sequence.length() * 5, expected.length);
        assertArrayEquals(expected, actual);
    }

    private static double[] loadProfileFixture(String resourcePath) throws IOException {
        InputStream stream = CapRTest.class.getResourceAsStream(resourcePath);
        assertNotNull(stream, "Missing fixture " + resourcePath);

        try (DataInputStream input = new DataInputStream(Objects.requireNonNull(stream))) {
            int count = input.readInt();
            double[] values = new double[count];

            for (int i = 0; i < count; i++) {
                values[i] = input.readDouble();
            }

            return values;
        }
    }
}
